USE [master]
GO

/****** Object:  Database [AddressBook]    Script Date: 7/8/2021 9:14:51 PM ******/
CREATE DATABASE [AddressBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AddressBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.KOLOB\MSSQL\DATA\AddressBook.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AddressBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.KOLOB\MSSQL\DATA\AddressBook_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AddressBook] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AddressBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AddressBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AddressBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AddressBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AddressBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AddressBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [AddressBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AddressBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AddressBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AddressBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AddressBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AddressBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AddressBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AddressBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AddressBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AddressBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AddressBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AddressBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AddressBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AddressBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AddressBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AddressBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AddressBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AddressBook] SET RECOVERY FULL 
GO

ALTER DATABASE [AddressBook] SET  MULTI_USER 
GO

ALTER DATABASE [AddressBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AddressBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AddressBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AddressBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AddressBook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AddressBook] SET  READ_WRITE 
GO


